### PR TITLE
Update dependencies and fix errors

### PR DESCRIPTION
**Pull request by WissamProgress**
Related to https://github.com/telerik/kendo-react-private/issues/2052

### CODE REVIEW

**Comment by WissamProgress** [comment]
Issues left to fix:
- [] dependency conflict
- [ ] fonts and styles are not applied

**Comment by vveesseelliinnaa** [comment]
Great work, Sami! Can you just delete the `package-lock.json` from the commit? You can also update the .gitignore file to exclude `package-lock.json` and `yarn.lock` files from the future commits automatically.

**Comment by WissamProgress** [comment]
Problem with black color instead of white:
-I tried using our KendoReact CheckBox component instead of input type='checkbox', but the checked icon has a black color (in the stock list)
-selecting a page in the grid pager (in virtualized) makes the color of the number black instead of white

I tried fixing that with CSS but it was not being applied

**Comment by WissamProgress** [comment]
I couldn't reproduce the exact same styles for the three buttons in Navigation.tsx (as the previous version) using themeColor and fillMode.
Can I style them with CSS instead?

**Comment by WissamProgress** [comment]
I could not find the origin of the black color. I check if the default theme is applied or any black styles used inside the styling files but could not find.
So I changed the color to black in main.scss in multiple components.

**Review by vveesseelliinnaa — APPROVED** [review]

**Pull request merged**
